import { Report } from './models/Report.js';

export async function seedData() {
  console.log("Seeding municipal issues data...");
  try {
    await Report.deleteMany();

    const sampleIssues = [
      {
        _id: 'issue_andhra_pradesh_1',
        title: 'Severe Cracking and Pothole on Main Road in Andhra Pradesh',
        description: 'A deep crater-like pothole has formed, causing severe traffic slowing and active swerving hazards.',
        category: 'Roads & Traffic',
        latitude: '15.9129',
        longitude: '79.74',
        state: 'Andhra Pradesh',
        imageUrl: 'https://images.unsplash.com/photo-1515162305285-0293e4767cc2?auto=format&fit=crop&q=80&w=800',
        isGenuine: true,
        severity: 'Critical' as const,
        issueType: 'Craters & Deep Road Cavity',
        recommendedAction: 'Deploy Quick Asphalt Patching Crew with hot-mix truck. Apply structural grade filling.',
        targetDepartment: 'Roads Department',
        status: 'Open' as const,
        upvotes: 66,
        aiSummary: 'A critical asphalt cavity presenting immediate safety hazards to commuter vehicles.',
        createdAt: new Date(Date.now() - 3600000 * 60).toISOString(),
      },
      {
        _id: 'issue_arunachal_pradesh_1',
        title: 'Active Water Pipe Leakage & Street Flooding in Arunachal Pradesh',
        description: 'A main utility water pipeline has ruptured, spraying fresh water and flooding the sidewalk and parking spots.',
        category: 'Water & Sewerage',
        latitude: '28.218',
        longitude: '94.7278',
        state: 'Arunachal Pradesh',
        imageUrl: 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&q=80&w=800',
        isGenuine: true,
        severity: 'High' as const,
        issueType: 'Ruptured Water Main Pipeline',
        recommendedAction: 'Isolate water sector, dispatch repair technicians, and execute valve replacement.',
        targetDepartment: 'Hydraulics Department',
        status: 'Verifying' as const,
        upvotes: 19,
        aiSummary: 'A major utility line rupture causing flooding and loss of drinking water supply pressure.',
        createdAt: new Date(Date.now() - 3600000 * 44).toISOString(),
      },
      {
        _id: 'issue_assam_1',
        title: 'Massive Waste Overflow on Public Bin in Assam',
        description: 'The community garbage collection bin has fully overflowed. Plastic waste and debris are spilled onto the road.',
        category: 'Solid Waste Management',
        latitude: '26.2006',
        longitude: '92.9376',
        state: 'Assam',
        imageUrl: 'https://images.unsplash.com/photo-1611284446314-60a58ac0deb9?auto=format&fit=crop&q=80&w=800',
        isGenuine: true,
        severity: 'Medium' as const,
        issueType: 'Uncontrolled Solid Waste Accumulation',
        recommendedAction: 'Dispatch Sanitation Dumper Truck. Conduct full manual sweep and chemical spot disinfection.',
        targetDepartment: 'Sanitation Division',
        status: 'Resolved' as const,
        upvotes: 95,
        aiSummary: 'Uncollected refuse overflowing in high-traffic zone, creating sanitary hazards and blocking public sidewalks.',
        createdAt: new Date(Date.now() - 3600000 * 60).toISOString(),
      },
      {
        _id: 'issue_bihar_1',
        title: 'Sparking Overhead Electric Wires near Crossing in Bihar',
        description: 'Overhead power cables are hanging dangerously low from an electric pole. Active sparking observed during light rainfall.',
        category: 'Electricity & Lighting',
        latitude: '25.0961',
        longitude: '85.3131',
        state: 'Bihar',
        imageUrl: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&q=80&w=800',
        isGenuine: true,
        severity: 'Critical' as const,
        issueType: 'Hanging Exposed Power Lines',
        recommendedAction: 'Cut electrical loop immediately, send Emergency Cable Crew, and re-tension the overhead pole cables.',
        targetDepartment: 'Engineering Board',
        status: 'Open' as const,
        upvotes: 5,
        aiSummary: 'Critical power cable spark and sagging hazards above pedestrian crossing. Requires immediate grid isolation and restructuring.',
        createdAt: new Date(Date.now() - 3600000 * 64).toISOString(),
      },
      {
        _id: 'issue_chhattisgarh_1',
        title: 'Severe Cracking and Pothole on Main Road in Chhattisgarh',
        description: 'A deep crater-like pothole has formed, causing severe traffic slowing and active swerving hazards.',
        category: 'Roads & Traffic',
        latitude: '21.2787',
        longitude: '81.8661',
        state: 'Chhattisgarh',
        imageUrl: 'https://images.unsplash.com/photo-1515162305285-0293e4767cc2?auto=format&fit=crop&q=80&w=800',
        isGenuine: true,
        severity: 'Critical' as const,
        issueType: 'Craters & Deep Road Cavity',
        recommendedAction: 'Deploy Quick Asphalt Patching Crew with hot-mix truck. Apply structural grade filling.',
        targetDepartment: 'Roads Department',
        status: 'Verifying' as const,
        upvotes: 51,
        aiSummary: 'A critical asphalt cavity presenting immediate safety hazards to commuter vehicles.',
        createdAt: new Date(Date.now() - 3600000 * 7).toISOString(),
      },
      {
        _id: 'issue_goa_1',
        title: 'Active Water Pipe Leakage & Street Flooding in Goa',
        description: 'A main utility water pipeline has ruptured, spraying fresh water and flooding the sidewalk and parking spots.',
        category: 'Water & Sewerage',
        latitude: '15.2993',
        longitude: '74.124',
        state: 'Goa',
        imageUrl: 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&q=80&w=800',
        isGenuine: true,
        severity: 'High' as const,
        issueType: 'Ruptured Water Main Pipeline',
        recommendedAction: 'Isolate water sector, dispatch repair technicians, and execute valve replacement.',
        targetDepartment: 'Hydraulics Department',
        status: 'Resolved' as const,
        upvotes: 75,
        aiSummary: 'A major utility line rupture causing flooding and loss of drinking water supply pressure.',
        createdAt: new Date(Date.now() - 3600000 * 36).toISOString(),
      },
      {
        _id: 'issue_gujarat_1',
        title: 'Massive Waste Overflow on Public Bin in Gujarat',
        description: 'The community garbage collection bin has fully overflowed. Plastic waste and debris are spilled onto the road.',
        category: 'Solid Waste Management',
        latitude: '22.2587',
        longitude: '71.1924',
        state: 'Gujarat',
        imageUrl: 'https://images.unsplash.com/photo-1611284446314-60a58ac0deb9?auto=format&fit=crop&q=80&w=800',
        isGenuine: true,
        severity: 'Medium' as const,
        issueType: 'Uncontrolled Solid Waste Accumulation',
        recommendedAction: 'Dispatch Sanitation Dumper Truck. Conduct full manual sweep and chemical spot disinfection.',
        targetDepartment: 'Sanitation Division',
        status: 'Open' as const,
        upvotes: 51,
        aiSummary: 'Uncollected refuse overflowing in high-traffic zone, creating sanitary hazards and blocking public sidewalks.',
        createdAt: new Date(Date.now() - 3600000 * 5).toISOString(),
      },
      {
        _id: 'issue_haryana_1',
        title: 'Sparking Overhead Electric Wires near Crossing in Haryana',
        description: 'Overhead power cables are hanging dangerously low from an electric pole. Active sparking observed during light rainfall.',
        category: 'Electricity & Lighting',
        latitude: '29.0588',
        longitude: '76.0856',
        state: 'Haryana',
        imageUrl: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&q=80&w=800',
        isGenuine: true,
        severity: 'Critical' as const,
        issueType: 'Hanging Exposed Power Lines',
        recommendedAction: 'Cut electrical loop immediately, send Emergency Cable Crew, and re-tension the overhead pole cables.',
        targetDepartment: 'Engineering Board',
        status: 'Verifying' as const,
        upvotes: 33,
        aiSummary: 'Critical power cable spark and sagging hazards above pedestrian crossing. Requires immediate grid isolation and restructuring.',
        createdAt: new Date(Date.now() - 3600000 * 40).toISOString(),
      },
      {
        _id: 'issue_himachal_pradesh_1',
        title: 'Severe Cracking and Pothole on Main Road in Himachal Pradesh',
        description: 'A deep crater-like pothole has formed, causing severe traffic slowing and active swerving hazards.',
        category: 'Roads & Traffic',
        latitude: '31.1048',
        longitude: '77.1665',
        state: 'Himachal Pradesh',
        imageUrl: 'https://images.unsplash.com/photo-1515162305285-0293e4767cc2?auto=format&fit=crop&q=80&w=800',
        isGenuine: true,
        severity: 'Critical' as const,
        issueType: 'Craters & Deep Road Cavity',
        recommendedAction: 'Deploy Quick Asphalt Patching Crew with hot-mix truck. Apply structural grade filling.',
        targetDepartment: 'Roads Department',
        status: 'Resolved' as const,
        upvotes: 65,
        aiSummary: 'A critical asphalt cavity presenting immediate safety hazards to commuter vehicles.',
        createdAt: new Date(Date.now() - 3600000 * 13).toISOString(),
      },
      {
        _id: 'issue_jharkhand_1',
        title: 'Active Water Pipe Leakage & Street Flooding in Jharkhand',
        description: 'A main utility water pipeline has ruptured, spraying fresh water and flooding the sidewalk and parking spots.',
        category: 'Water & Sewerage',
        latitude: '23.6102',
        longitude: '85.2799',
        state: 'Jharkhand',
        imageUrl: 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&q=80&w=800',
        isGenuine: true,
        severity: 'High' as const,
        issueType: 'Ruptured Water Main Pipeline',
        recommendedAction: 'Isolate water sector, dispatch repair technicians, and execute valve replacement.',
        targetDepartment: 'Hydraulics Department',
        status: 'Open' as const,
        upvotes: 87,
        aiSummary: 'A major utility line rupture causing flooding and loss of drinking water supply pressure.',
        createdAt: new Date(Date.now() - 3600000 * 46).toISOString(),
      },
      {
        _id: 'issue_kerala_1',
        title: 'Massive Waste Overflow on Public Bin in Kerala',
        description: 'The community garbage collection bin has fully overflowed. Plastic waste and debris are spilled onto the road.',
        category: 'Solid Waste Management',
        latitude: '10.8505',
        longitude: '76.2711',
        state: 'Kerala',
        imageUrl: 'https://images.unsplash.com/photo-1611284446314-60a58ac0deb9?auto=format&fit=crop&q=80&w=800',
        isGenuine: true,
        severity: 'Medium' as const,
        issueType: 'Uncontrolled Solid Waste Accumulation',
        recommendedAction: 'Dispatch Sanitation Dumper Truck. Conduct full manual sweep and chemical spot disinfection.',
        targetDepartment: 'Sanitation Division',
        status: 'Verifying' as const,
        upvotes: 94,
        aiSummary: 'Uncollected refuse overflowing in high-traffic zone, creating sanitary hazards and blocking public sidewalks.',
        createdAt: new Date(Date.now() - 3600000 * 16).toISOString(),
      },
      {
        _id: 'issue_madhya_pradesh_1',
        title: 'Sparking Overhead Electric Wires near Crossing in Madhya Pradesh',
        description: 'Overhead power cables are hanging dangerously low from an electric pole. Active sparking observed during light rainfall.',
        category: 'Electricity & Lighting',
        latitude: '22.9734',
        longitude: '78.6569',
        state: 'Madhya Pradesh',
        imageUrl: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&q=80&w=800',
        isGenuine: true,
        severity: 'Critical' as const,
        issueType: 'Hanging Exposed Power Lines',
        recommendedAction: 'Cut electrical loop immediately, send Emergency Cable Crew, and re-tension the overhead pole cables.',
        targetDepartment: 'Engineering Board',
        status: 'Resolved' as const,
        upvotes: 90,
        aiSummary: 'Critical power cable spark and sagging hazards above pedestrian crossing. Requires immediate grid isolation and restructuring.',
        createdAt: new Date(Date.now() - 3600000 * 40).toISOString(),
      },
      {
        _id: 'issue_manipur_1',
        title: 'Severe Cracking and Pothole on Main Road in Manipur',
        description: 'A deep crater-like pothole has formed, causing severe traffic slowing and active swerving hazards.',
        category: 'Roads & Traffic',
        latitude: '24.6637',
        longitude: '93.9063',
        state: 'Manipur',
        imageUrl: 'https://images.unsplash.com/photo-1515162305285-0293e4767cc2?auto=format&fit=crop&q=80&w=800',
        isGenuine: true,
        severity: 'Critical' as const,
        issueType: 'Craters & Deep Road Cavity',
        recommendedAction: 'Deploy Quick Asphalt Patching Crew with hot-mix truck. Apply structural grade filling.',
        targetDepartment: 'Roads Department',
        status: 'Open' as const,
        upvotes: 7,
        aiSummary: 'A critical asphalt cavity presenting immediate safety hazards to commuter vehicles.',
        createdAt: new Date(Date.now() - 3600000 * 19).toISOString(),
      },
      {
        _id: 'issue_meghalaya_1',
        title: 'Active Water Pipe Leakage & Street Flooding in Meghalaya',
        description: 'A main utility water pipeline has ruptured, spraying fresh water and flooding the sidewalk and parking spots.',
        category: 'Water & Sewerage',
        latitude: '25.467',
        longitude: '91.3662',
        state: 'Meghalaya',
        imageUrl: 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&q=80&w=800',
        isGenuine: true,
        severity: 'High' as const,
        issueType: 'Ruptured Water Main Pipeline',
        recommendedAction: 'Isolate water sector, dispatch repair technicians, and execute valve replacement.',
        targetDepartment: 'Hydraulics Department',
        status: 'Verifying' as const,
        upvotes: 64,
        aiSummary: 'A major utility line rupture causing flooding and loss of drinking water supply pressure.',
        createdAt: new Date(Date.now() - 3600000 * 54).toISOString(),
      },
      {
        _id: 'issue_mizoram_1',
        title: 'Massive Waste Overflow on Public Bin in Mizoram',
        description: 'The community garbage collection bin has fully overflowed. Plastic waste and debris are spilled onto the road.',
        category: 'Solid Waste Management',
        latitude: '23.1645',
        longitude: '92.9376',
        state: 'Mizoram',
        imageUrl: 'https://images.unsplash.com/photo-1611284446314-60a58ac0deb9?auto=format&fit=crop&q=80&w=800',
        isGenuine: true,
        severity: 'Medium' as const,
        issueType: 'Uncontrolled Solid Waste Accumulation',
        recommendedAction: 'Dispatch Sanitation Dumper Truck. Conduct full manual sweep and chemical spot disinfection.',
        targetDepartment: 'Sanitation Division',
        status: 'Resolved' as const,
        upvotes: 34,
        aiSummary: 'Uncollected refuse overflowing in high-traffic zone, creating sanitary hazards and blocking public sidewalks.',
        createdAt: new Date(Date.now() - 3600000 * 14).toISOString(),
      },
      {
        _id: 'issue_nagaland_1',
        title: 'Sparking Overhead Electric Wires near Crossing in Nagaland',
        description: 'Overhead power cables are hanging dangerously low from an electric pole. Active sparking observed during light rainfall.',
        category: 'Electricity & Lighting',
        latitude: '26.1584',
        longitude: '94.5624',
        state: 'Nagaland',
        imageUrl: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&q=80&w=800',
        isGenuine: true,
        severity: 'Critical' as const,
        issueType: 'Hanging Exposed Power Lines',
        recommendedAction: 'Cut electrical loop immediately, send Emergency Cable Crew, and re-tension the overhead pole cables.',
        targetDepartment: 'Engineering Board',
        status: 'Open' as const,
        upvotes: 15,
        aiSummary: 'Critical power cable spark and sagging hazards above pedestrian crossing. Requires immediate grid isolation and restructuring.',
        createdAt: new Date(Date.now() - 3600000 * 0).toISOString(),
      },
      {
        _id: 'issue_odisha_1',
        title: 'Severe Cracking and Pothole on Main Road in Odisha',
        description: 'A deep crater-like pothole has formed, causing severe traffic slowing and active swerving hazards.',
        category: 'Roads & Traffic',
        latitude: '20.9517',
        longitude: '85.0985',
        state: 'Odisha',
        imageUrl: 'https://images.unsplash.com/photo-1515162305285-0293e4767cc2?auto=format&fit=crop&q=80&w=800',
        isGenuine: true,
        severity: 'Critical' as const,
        issueType: 'Craters & Deep Road Cavity',
        recommendedAction: 'Deploy Quick Asphalt Patching Crew with hot-mix truck. Apply structural grade filling.',
        targetDepartment: 'Roads Department',
        status: 'Verifying' as const,
        upvotes: 59,
        aiSummary: 'A critical asphalt cavity presenting immediate safety hazards to commuter vehicles.',
        createdAt: new Date(Date.now() - 3600000 * 67).toISOString(),
      },
      {
        _id: 'issue_punjab_1',
        title: 'Active Water Pipe Leakage & Street Flooding in Punjab',
        description: 'A main utility water pipeline has ruptured, spraying fresh water and flooding the sidewalk and parking spots.',
        category: 'Water & Sewerage',
        latitude: '31.1471',
        longitude: '75.3412',
        state: 'Punjab',
        imageUrl: 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&q=80&w=800',
        isGenuine: true,
        severity: 'High' as const,
        issueType: 'Ruptured Water Main Pipeline',
        recommendedAction: 'Isolate water sector, dispatch repair technicians, and execute valve replacement.',
        targetDepartment: 'Hydraulics Department',
        status: 'Resolved' as const,
        upvotes: 95,
        aiSummary: 'A major utility line rupture causing flooding and loss of drinking water supply pressure.',
        createdAt: new Date(Date.now() - 3600000 * 7).toISOString(),
      },
      {
        _id: 'issue_rajasthan_1',
        title: 'Massive Waste Overflow on Public Bin in Rajasthan',
        description: 'The community garbage collection bin has fully overflowed. Plastic waste and debris are spilled onto the road.',
        category: 'Solid Waste Management',
        latitude: '27.0238',
        longitude: '74.2179',
        state: 'Rajasthan',
        imageUrl: 'https://images.unsplash.com/photo-1611284446314-60a58ac0deb9?auto=format&fit=crop&q=80&w=800',
        isGenuine: true,
        severity: 'Medium' as const,
        issueType: 'Uncontrolled Solid Waste Accumulation',
        recommendedAction: 'Dispatch Sanitation Dumper Truck. Conduct full manual sweep and chemical spot disinfection.',
        targetDepartment: 'Sanitation Division',
        status: 'Open' as const,
        upvotes: 32,
        aiSummary: 'Uncollected refuse overflowing in high-traffic zone, creating sanitary hazards and blocking public sidewalks.',
        createdAt: new Date(Date.now() - 3600000 * 57).toISOString(),
      },
      {
        _id: 'issue_sikkim_1',
        title: 'Sparking Overhead Electric Wires near Crossing in Sikkim',
        description: 'Overhead power cables are hanging dangerously low from an electric pole. Active sparking observed during light rainfall.',
        category: 'Electricity & Lighting',
        latitude: '27.533',
        longitude: '88.5122',
        state: 'Sikkim',
        imageUrl: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&q=80&w=800',
        isGenuine: true,
        severity: 'Critical' as const,
        issueType: 'Hanging Exposed Power Lines',
        recommendedAction: 'Cut electrical loop immediately, send Emergency Cable Crew, and re-tension the overhead pole cables.',
        targetDepartment: 'Engineering Board',
        status: 'Verifying' as const,
        upvotes: 42,
        aiSummary: 'Critical power cable spark and sagging hazards above pedestrian crossing. Requires immediate grid isolation and restructuring.',
        createdAt: new Date(Date.now() - 3600000 * 17).toISOString(),
      },
      {
        _id: 'issue_tamil_nadu_1',
        title: 'Severe Cracking and Pothole on Main Road in Tamil Nadu',
        description: 'A deep crater-like pothole has formed, causing severe traffic slowing and active swerving hazards.',
        category: 'Roads & Traffic',
        latitude: '11.1271',
        longitude: '78.6569',
        state: 'Tamil Nadu',
        imageUrl: 'https://images.unsplash.com/photo-1515162305285-0293e4767cc2?auto=format&fit=crop&q=80&w=800',
        isGenuine: true,
        severity: 'Critical' as const,
        issueType: 'Craters & Deep Road Cavity',
        recommendedAction: 'Deploy Quick Asphalt Patching Crew with hot-mix truck. Apply structural grade filling.',
        targetDepartment: 'Roads Department',
        status: 'Resolved' as const,
        upvotes: 53,
        aiSummary: 'A critical asphalt cavity presenting immediate safety hazards to commuter vehicles.',
        createdAt: new Date(Date.now() - 3600000 * 8).toISOString(),
      },
      {
        _id: 'issue_telangana_1',
        title: 'Active Water Pipe Leakage & Street Flooding in Telangana',
        description: 'A main utility water pipeline has ruptured, spraying fresh water and flooding the sidewalk and parking spots.',
        category: 'Water & Sewerage',
        latitude: '18.1124',
        longitude: '79.0193',
        state: 'Telangana',
        imageUrl: 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&q=80&w=800',
        isGenuine: true,
        severity: 'High' as const,
        issueType: 'Ruptured Water Main Pipeline',
        recommendedAction: 'Isolate water sector, dispatch repair technicians, and execute valve replacement.',
        targetDepartment: 'Hydraulics Department',
        status: 'Open' as const,
        upvotes: 99,
        aiSummary: 'A major utility line rupture causing flooding and loss of drinking water supply pressure.',
        createdAt: new Date(Date.now() - 3600000 * 16).toISOString(),
      },
      {
        _id: 'issue_tripura_1',
        title: 'Massive Waste Overflow on Public Bin in Tripura',
        description: 'The community garbage collection bin has fully overflowed. Plastic waste and debris are spilled onto the road.',
        category: 'Solid Waste Management',
        latitude: '23.9408',
        longitude: '91.9882',
        state: 'Tripura',
        imageUrl: 'https://images.unsplash.com/photo-1611284446314-60a58ac0deb9?auto=format&fit=crop&q=80&w=800',
        isGenuine: true,
        severity: 'Medium' as const,
        issueType: 'Uncontrolled Solid Waste Accumulation',
        recommendedAction: 'Dispatch Sanitation Dumper Truck. Conduct full manual sweep and chemical spot disinfection.',
        targetDepartment: 'Sanitation Division',
        status: 'Verifying' as const,
        upvotes: 30,
        aiSummary: 'Uncollected refuse overflowing in high-traffic zone, creating sanitary hazards and blocking public sidewalks.',
        createdAt: new Date(Date.now() - 3600000 * 3).toISOString(),
      },
      {
        _id: 'issue_uttar_pradesh_1',
        title: 'Sparking Overhead Electric Wires near Crossing in Uttar Pradesh',
        description: 'Overhead power cables are hanging dangerously low from an electric pole. Active sparking observed during light rainfall.',
        category: 'Electricity & Lighting',
        latitude: '26.8467',
        longitude: '80.9462',
        state: 'Uttar Pradesh',
        imageUrl: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&q=80&w=800',
        isGenuine: true,
        severity: 'Critical' as const,
        issueType: 'Hanging Exposed Power Lines',
        recommendedAction: 'Cut electrical loop immediately, send Emergency Cable Crew, and re-tension the overhead pole cables.',
        targetDepartment: 'Engineering Board',
        status: 'Resolved' as const,
        upvotes: 96,
        aiSummary: 'Critical power cable spark and sagging hazards above pedestrian crossing. Requires immediate grid isolation and restructuring.',
        createdAt: new Date(Date.now() - 3600000 * 20).toISOString(),
      },
      {
        _id: 'issue_uttarakhand_1',
        title: 'Severe Cracking and Pothole on Main Road in Uttarakhand',
        description: 'A deep crater-like pothole has formed, causing severe traffic slowing and active swerving hazards.',
        category: 'Roads & Traffic',
        latitude: '30.0668',
        longitude: '79.0193',
        state: 'Uttarakhand',
        imageUrl: 'https://images.unsplash.com/photo-1515162305285-0293e4767cc2?auto=format&fit=crop&q=80&w=800',
        isGenuine: true,
        severity: 'Critical' as const,
        issueType: 'Craters & Deep Road Cavity',
        recommendedAction: 'Deploy Quick Asphalt Patching Crew with hot-mix truck. Apply structural grade filling.',
        targetDepartment: 'Roads Department',
        status: 'Open' as const,
        upvotes: 13,
        aiSummary: 'A critical asphalt cavity presenting immediate safety hazards to commuter vehicles.',
        createdAt: new Date(Date.now() - 3600000 * 17).toISOString(),
      },
      {
        _id: 'issue_delhi_1',
        title: 'Active Water Pipe Leakage & Street Flooding in Delhi',
        description: 'A main utility water pipeline has ruptured, spraying fresh water and flooding the sidewalk and parking spots.',
        category: 'Water & Sewerage',
        latitude: '28.6139',
        longitude: '77.209',
        state: 'Delhi',
        imageUrl: 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&q=80&w=800',
        isGenuine: true,
        severity: 'High' as const,
        issueType: 'Ruptured Water Main Pipeline',
        recommendedAction: 'Isolate water sector, dispatch repair technicians, and execute valve replacement.',
        targetDepartment: 'Hydraulics Department',
        status: 'Verifying' as const,
        upvotes: 77,
        aiSummary: 'A major utility line rupture causing flooding and loss of drinking water supply pressure.',
        createdAt: new Date(Date.now() - 3600000 * 35).toISOString(),
      },
      {
        _id: 'issue_maharashtra_1',
        title: 'Massive Waste Overflow on Public Bin in Maharashtra',
        description: 'The community garbage collection bin has fully overflowed. Plastic waste and debris are spilled onto the road.',
        category: 'Solid Waste Management',
        latitude: '19.076',
        longitude: '72.8777',
        state: 'Maharashtra',
        imageUrl: 'https://images.unsplash.com/photo-1611284446314-60a58ac0deb9?auto=format&fit=crop&q=80&w=800',
        isGenuine: true,
        severity: 'Medium' as const,
        issueType: 'Uncontrolled Solid Waste Accumulation',
        recommendedAction: 'Dispatch Sanitation Dumper Truck. Conduct full manual sweep and chemical spot disinfection.',
        targetDepartment: 'Sanitation Division',
        status: 'Resolved' as const,
        upvotes: 34,
        aiSummary: 'Uncollected refuse overflowing in high-traffic zone, creating sanitary hazards and blocking public sidewalks.',
        createdAt: new Date(Date.now() - 3600000 * 52).toISOString(),
      },
      {
        _id: 'issue_karnataka_1',
        title: 'Sparking Overhead Electric Wires near Crossing in Karnataka',
        description: 'Overhead power cables are hanging dangerously low from an electric pole. Active sparking observed during light rainfall.',
        category: 'Electricity & Lighting',
        latitude: '12.9716',
        longitude: '77.5946',
        state: 'Karnataka',
        imageUrl: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&q=80&w=800',
        isGenuine: true,
        severity: 'Critical' as const,
        issueType: 'Hanging Exposed Power Lines',
        recommendedAction: 'Cut electrical loop immediately, send Emergency Cable Crew, and re-tension the overhead pole cables.',
        targetDepartment: 'Engineering Board',
        status: 'Open' as const,
        upvotes: 52,
        aiSummary: 'Critical power cable spark and sagging hazards above pedestrian crossing. Requires immediate grid isolation and restructuring.',
        createdAt: new Date(Date.now() - 3600000 * 70).toISOString(),
      },
      {
        _id: 'issue_west_bengal_1',
        title: 'Severe Cracking and Pothole on Main Road in West Bengal',
        description: 'A deep crater-like pothole has formed, causing severe traffic slowing and active swerving hazards.',
        category: 'Roads & Traffic',
        latitude: '22.5726',
        longitude: '88.3639',
        state: 'West Bengal',
        imageUrl: 'https://images.unsplash.com/photo-1515162305285-0293e4767cc2?auto=format&fit=crop&q=80&w=800',
        isGenuine: true,
        severity: 'Critical' as const,
        issueType: 'Craters & Deep Road Cavity',
        recommendedAction: 'Deploy Quick Asphalt Patching Crew with hot-mix truck. Apply structural grade filling.',
        targetDepartment: 'Roads Department',
        status: 'Verifying' as const,
        upvotes: 47,
        aiSummary: 'A critical asphalt cavity presenting immediate safety hazards to commuter vehicles.',
        createdAt: new Date(Date.now() - 3600000 * 6).toISOString(),
      }
    ];

    for (const issue of sampleIssues) {
      await Report.create(issue);
    }

    console.log("Seeding completed successfully! 29 major Indian municipal reports injected.");
  } catch (error) {
    console.error("Error during seeding:", error);
  }
}

// Run directly if invoked via CLI
if (process.argv[1]?.endsWith('seed.ts') || process.argv[1]?.endsWith('seed.js')) {
  seedData().then(() => process.exit(0));
}
